#!/bin/bash
# Script that generates the assembly code (Intel syntax) of a C code

# Set the C file name
CFILE="main.c"

# Generate the assembly code using GCC and save it to a file
gcc -S -masm=intel "$CFILE"

# Rename the output file to match the C file name
mv "${CFILE%.*}.s" "$CFILE.s"

